# Configuration for FrugalIoT server
# Configuration for FrugalIoT server
server:
  port: 8080
mqtt:
  broker: ws://naturalinnovation.org:9012
organizations:
  dev:
    name: Development
    mqtt_password: public
    projects:
      Lotus Ponds:
        duplicates:
          time: true
        nodes:
          esp8266-85ea2b:
            topics:
              temperature:
              humidity:
          esp8266-95a754:
            topics:
              temperature:
              humidity:
          esp32-3c7ab8:
            topics:
              battery:


