# Configuration for FrugalIoT server for organization=dev
mqtt_password: public
name: Development
gsheets:
  - url: https://script.google.com/macros/s/AKfycbzlLfnR4tPgkoAmPZW-Z6F_J5PpTOG_U8Ip59qlo6OVYdIEOB3yvlF7GIJz1bANFW4/exec
    spreadsheet: https://docs.google.com/spreadsheets/d/1mPHvPFW4YwRvxtTQXP4fKKDjWbYN8JpeaIAVgeFIfgA
    intervalSeconds: 900
    topics:
      - dev/lotus/esp8266-fb94bb/sht/humidity
      - dev/lotus/esp8266-fb94bb/sht/temperature
projects:
  lotus:
    name: Lotus Ponds
    nodes:
      +:
        sub:
          +:
            topics:
              humidity:
                type: float
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              temperature:
                type: float
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              soil:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              soil2:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              soil3:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              battery:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 100
              relay:
                type: bool
              ledbuiltin:
                type: bool
              loadcell:
                type: float
              aqi:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              aqi500:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              tvoc:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              eco2:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              on:
                type: bool
  magi:
    name: Magi Farm
    nodes:
      +:
        sub:
          +:
            topics:
              humidity:
                type: float
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              temperature:
                type: float
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              soil:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              soil2:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              soil3:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              battery:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 100
  developers:
    name: Developers
    nodes:
      +:
        sub:
          +:
            topics:
              humidity:
                type: float
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              temperature:
                type: float
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              soil:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              soil2:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              soil3:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              battery:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 100
              relay:
                type: bool
              ledbuiltin:
                type: bool
              loadcell:
                type: float
              aqi:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              aqi500:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              tvoc:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              eco2:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              on:
                type: bool
