# Configuration for FrugalIoT server for organization=dev
mqtt_password: public
name: Development
projects:
  lotus:
    name: Lotus Ponds
    nodes:
      +:
        topics:
          humidity:
            type: float
            duplicates:
              significantdate: 900000
              significantvalue: 1
          temperature:
            type: float
            duplicates:
              significantdate: 900000
              significantvalue: 1
          soil:
            type: int
            duplicates:
              significantdate: 900000
              significantvalue: 1
          soil2:
            type: int
            duplicates:
              significantdate: 900000
              significantvalue: 1
          soil3:
            type: int
            duplicates:
              significantdate: 900000
              significantvalue: 1
          battery:
            type: int
            duplicates:
              significantdate: 900000
              significantvalue: 100
  magi:
    name: Magi Farm
    nodes:
      +:
        topics:
          humidity:
            type: float
            duplicates:
              significantdate: 900000
              significantvalue: 1
          temperature:
            type: float
            duplicates:
              significantdate: 900000
              significantvalue: 1
          soil:
            type: int
            duplicates:
              significantdate: 900000
              significantvalue: 1
          soil2:
            type: int
            duplicates:
              significantdate: 900000
              significantvalue: 1
          soil3:
            type: int
            duplicates:
              significantdate: 900000
              significantvalue: 1
          battery:
            type: int
            duplicates:
              significantdate: 900000
              significantvalue: 100
