# Configuration for FrugalIoT server for organization=dev
mqtt_password: public
name: Development
projects:
  lotus:
    name: Lotus Ponds
    nodes:
      +:
        sub:
          +:
            topics:
              humidity:
                type: float
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              temperature:
                type: float
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              soil:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              soil2:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              soil3:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              battery:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 100
              relay:
                type: bool
              ledbuiltin:
                type: bool
              loadcell:
                type: float
  magi:
    name: Magi Farm
    nodes:
      +:
        sub:
          +:
            topics:
              humidity:
                type: float
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              temperature:
                type: float
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              soil:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              soil2:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              soil3:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              battery:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 100
              aqi:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              aqi500:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              tvoc:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
              eco2:
                type: int
                duplicates:
                  significantdate: 900000
                  significantvalue: 1
