# Configuration for FrugalIoT server for organization=dev
mqtt_password: public
name: Development
gsheets:
  - url: https://script.google.com/macros/s/AKfycbzlLfnR4tPgkoAmPZW-Z6F_J5PpTOG_U8Ip59qlo6OVYdIEOB3yvlF7GIJz1bANFW4/exec
    spreadsheet: https://docs.google.com/spreadsheets/d/1mPHvPFW4YwRvxtTQXP4fKKDjWbYN8JpeaIAVgeFIfgA
    intervalSeconds: 900
    topics:
      - dev/lotus/esp8266-fb94bb/sht/humidity
      - dev/lotus/esp8266-fb94bb/sht/temperature
projects:
  lotus:
    name: Lotus Ponds
  developers:
    name: Developers
  umahpupa:
    name: Umah Pupa
